# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import three_el_pb2 as three__el__pb2


class RatingProviderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetProductClass = channel.unary_unary(
        '/RatingProvider/GetProductClass',
        request_serializer=three__el__pb2.ProductName.SerializeToString,
        response_deserializer=three__el__pb2.Classification.FromString,
        )


class RatingProviderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetProductClass(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RatingProviderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetProductClass': grpc.unary_unary_rpc_method_handler(
          servicer.GetProductClass,
          request_deserializer=three__el__pb2.ProductName.FromString,
          response_serializer=three__el__pb2.Classification.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'RatingProvider', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
