dist: xenial
language: python
python: 3.6
install:
  - pip3 install --upgrade pip
  - source backend/.env
  - pip install -r backend/requirements.txt
  - pip install -U pytest
  - python backend/setup.py
script:
  - pytest backend/src/tests.py
